language: R
sudo: false
cache: packages

r:
- 3.3

r-packages:
  - data.table
  - ggplot2

bioc_packages:
  - Biostrings
  - GenomicAlignments
  - GenomicFeatures
  - GenomicRanges

notifications:
  email:
    on_success: never
    on_failure: never